[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
aggregator = { path = "../aggregator" }
collector_core = { path = "../core", package = "core" }
writer = { path = "../writer" }
serde_json = "1.0"
